sudo: required
services:
  - docker
before_install:
  - docker pull yglukhov/nim-ui-base
script:
  - docker run -v "$(pwd):/project" -w /project yglukhov/devel run "nimble install -y && nake tests && nake tests -d:js && nake js --norun && nake docs"
  - ./deployGHPages.sh ./doc
